apiVersion: v1
kind: ConfigMap
metadata:
  name: single-app-single-collector
  labels:
    app: single-app-single-collector
  namespace: metrics
data:
  OTEL_SERVICE_NAME: "single-app-single-collector-fastapi-app"
  OTEL_TRACES_EXPORTER: "console,otlp"
  OTEL_METRICS_EXPORTER: "console,otlp"
  OTEL_LOGS_EXPORTER: "console,otlp"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-k8s-monitoring-alloy.metrics.svc.cluster.local:4317"
  OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"